"use client";

import { useState } from "react";
import { LoaderCircle, LockKeyhole } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { formatPrice } from "@/lib/demo-data";

export function CheckoutForm(){const {cart}=useCart();const [loading,setLoading]=useState(false);const [error,setError]=useState("");if(!cart)return <div className="py-24 text-center"><h1 className="text-4xl font-semibold">Your hold is empty.</h1><a href="/shop" className="mt-6 inline-block border-b border-black pb-1">Return to the shop</a></div>;return <form onSubmit={async(e)=>{e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);const response=await fetch("/api/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemId:cart.item.id,reservationToken:cart.token,email:form.get("email"),name:form.get("name"),address:{line1:form.get("address"),city:form.get("city"),postalCode:form.get("postalCode")}})});const payload=await response.json();if(response.ok&&payload.url)location.href=payload.url;else{setError(payload.error??"Checkout could not be started.");setLoading(false)}}} className="grid gap-8 lg:grid-cols-[1fr_420px]"><div><h1 className="display text-6xl md:text-8xl">Checkout</h1><p className="mt-5 max-w-lg opacity-60">Complete your details before your fifteen-minute hold expires.</p><div className="mt-10 grid gap-5"><Field label="Email" name="email" type="email"/><Field label="Full name" name="name"/><Field label="Street address" name="address"/><div className="grid grid-cols-2 gap-4"><Field label="City" name="city"/><Field label="Postal code" name="postalCode"/></div></div></div><aside className="h-fit border hairline p-6"><p className="eyebrow">Order summary</p><div className="my-6 border-y hairline py-5"><p className="font-semibold">{cart.item.title}</p><p className="mt-1 text-xs opacity-55">One-off item · Qty 1</p></div><div className="flex justify-between font-mono"><span>Total</span><span>{formatPrice(cart.item.price)}</span></div><button disabled={loading} className="mt-6 flex w-full items-center justify-center gap-2 bg-[var(--ink)] py-4 text-white disabled:opacity-50">{loading?<LoaderCircle className="animate-spin" size={18}/>:<LockKeyhole size={17}/>} Continue to secure payment</button>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<p className="mt-4 text-center text-[10px] uppercase tracking-wider opacity-45">Encrypted checkout powered by Stripe</p></aside></form>}
function Field({label,name,type="text"}:{label:string;name:string;type?:string}){return <label className="grid gap-2 text-xs font-medium">{label}<input required name={name} type={type} className="border-b hairline bg-transparent px-1 py-3 text-base outline-none focus:border-black"/></label>}
