import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft, ShieldCheck, Truck } from "lucide-react";
import { AddToCart } from "@/components/add-to-cart";
import { ProductCard } from "@/components/product-card";
import { getItem, getItems } from "@/lib/data";
import { formatPrice } from "@/lib/demo-data";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=await getItem((await params).slug);return item?{title:item.title,description:item.description,openGraph:{images:item.images}}:{title:"Piece not found"}}
export default async function ItemPage({params}:{params:Promise<{slug:string}>}) { const item=await getItem((await params).slug); if(!item)notFound(); const related=(await getItems()).filter(x=>x.category===item.category&&x.id!==item.id).slice(0,3); return <main><div className="mx-auto max-w-[1600px] px-4 py-5 md:px-8"><Link href="/shop" className="inline-flex items-center gap-1 text-xs"><ChevronLeft size={15}/> Back to the edit</Link></div><section className="mx-auto grid max-w-[1600px] lg:grid-cols-[1.5fr_1fr]"><div className="grid gap-1 md:grid-cols-2">{item.images.map((src,index)=><div key={src} className={`relative overflow-hidden bg-[#dedbd1] ${index===0&&item.images.length===1?"md:col-span-2 aspect-[4/3]":"aspect-[4/5]"}`}><Image src={src} alt={`${item.title}, view ${index+1}`} fill priority={index===0} sizes="(max-width:1024px) 100vw, 60vw" className="object-cover"/></div>)}</div><aside className="p-6 md:p-10 lg:sticky lg:top-16 lg:h-[calc(100vh-4rem)] lg:overflow-y-auto"><p className="eyebrow">{item.category} · {item.condition}</p><h1 className="mt-4 text-[clamp(2.5rem,5vw,5rem)] font-semibold leading-[.95] tracking-[-.06em]">{item.title}</h1><p className="mt-6 font-mono text-lg">{formatPrice(item.price)}</p>{item.size&&<div className="mt-8 border-y hairline py-4 text-sm"><span className="opacity-50">Size</span><span className="float-right font-medium">{item.size}</span></div>}<p className="mt-8 text-sm leading-7 opacity-70">{item.description}</p><div className="mt-9"><AddToCart item={item}/></div><div className="mt-8 grid gap-4 border-t hairline pt-6 text-xs"><p className="flex gap-3"><ShieldCheck size={18}/><span><b className="block">Inspected by REGEAR</b><span className="opacity-55">Condition checked and photographed in-house.</span></span></p><p className="flex gap-3"><Truck size={18}/><span><b className="block">Nationwide delivery</b><span className="opacity-55">Tracked shipping from Metro Manila.</span></span></p></div></aside></section>{related.length>0&&<section className="mx-auto max-w-[1600px] px-4 py-28 md:px-8 md:py-40"><h2 className="display mb-10 text-5xl md:text-7xl">Same energy</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-3">{related.map(i=><ProductCard item={i} key={i.id}/>)}</div></section>}</main> }
